module ShardBroker
  module Status
    PARSER_ERROR              = "PARSER_ERROR"
    TIMEOUT_ERROR             = "TIMEOUT_ERROR"
    UNDEFINED_COMMAND_ERROR   = "UNDEFINED_COMMAND_ERROR"
    NO_ID_ATTRIBUTE           = "NO_ID_ATTRIBUTE"
    INVALID_ACTION_PACKAGE    = "INVALID_ACTION_PACKAGE"
    AUTH_REQUIRED             = "AUTH_REQUIRED"
    UNSUPPORTED_TYPE_ERROR    = "UNSUPPORTED_TYPE_ERROR"
    INVALID_PASSWORD_ERROR    = "INVALID_PASSWORD_ERROR"
    REGISTRATION_ERROR        = "REGISTRATION_ERROR"
    SUCCESS                   = "SUCCESS"
  end
end